### ISSUE TITLE
NPM : not a valid npm package 

### ISSUE THREAD

**Issue by Chokapix** [tiburon-security/jupyterlab_scheduler#1]
Hello !

I'm trying to install your extension but it seems like it's not published yet in the npm registry :
> jupyter labextension install jupyterlab_scheduler

>An error occured.
ValueError: "jupyterlab_scheduler" is not a valid npm package

>Node v13.13.0
Yarn configuration loaded.
 /opt/conda/bin/npm pack jupyterlab_scheduler
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/jupyterlab_scheduler - Not found
npm ERR! 404 
npm ERR! 404  'jupyterlab_scheduler@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

Is it published yet ?

Thanks :)

**Comment by jovanni-hernandez** [comment]
I haven't had a chance to bundle it as an npm package, but try:

pip install jupyterlab_scheduler

then

jupyter labextension install jupyterlab_scheduler

**Comment by jovanni-hernandez** [comment]
To install:

```
pip install jupyterlab_scheduler
jupyter labextension install jupyterlab_scheduler
```

**Comment by lingsamuel** [comment]
Still get this error even ran `pip install jupyterlab_scheduler` first.

**Comment by ea5055** [comment]
Getting the same error. Tried pip install and also using it in developer mode.  I'm on a macOS if that makes a difference.

**Comment by analphabit** [comment]
I am getting the npm error as well.

How can we fix this and get the extension running?

Thx

**Comment by oskrdt** [comment]
> To install:
> 
> ```
> pip install jupyterlab_scheduler
> jupyter labextension install jupyterlab_scheduler
> ```

@jovanni-hernandez I followed your recommendation and I'm still getting the same error
```
$ pip install jupyterlab_scheduler
Requirement already satisfied: jupyterlab_scheduler in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (0.1.3)
Requirement already satisfied: jupyterlab~=2.0 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jupyterlab_scheduler) (2.2.9)
Requirement already satisfied: python-crontab~=2.5 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jupyterlab_scheduler) (2.5.1)
Requirement already satisfied: papermill~=2.1 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jupyterlab_scheduler) (2.3.1)
Requirement already satisfied: jupyterlab-server<2.0,>=1.1.5 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jupyterlab~=2.0->jupyterlab_scheduler) (1.2.0)
Requirement already satisfied: notebook>=4.3.1 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jupyterlab~=2.0->jupyterlab_scheduler) (6.2.0)
Requirement already satisfied: tornado!=6.0.0,!=6.0.1,!=6.0.2 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jupyterlab~=2.0->jupyterlab_scheduler) (6.1)
Requirement already satisfied: jinja2>=2.10 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jupyterlab~=2.0->jupyterlab_scheduler) (2.11.2)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jinja2>=2.10->jupyterlab~=2.0->jupyterlab_scheduler) (1.1.1)
Requirement already satisfied: requests in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jupyterlab-server<2.0,>=1.1.5->jupyterlab~=2.0->jupyterlab_scheduler) (2.25.1)
Requirement already satisfied: jsonschema>=3.0.1 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jupyterlab-server<2.0,>=1.1.5->jupyterlab~=2.0->jupyterlab_scheduler) (3.2.0)
Requirement already satisfied: json5 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jupyterlab-server<2.0,>=1.1.5->jupyterlab~=2.0->jupyterlab_scheduler) (0.9.5)
Requirement already satisfied: six>=1.11.0 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab~=2.0->jupyterlab_scheduler) (1.15.0)
Requirement already satisfied: attrs>=17.4.0 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab~=2.0->jupyterlab_scheduler) (20.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab~=2.0->jupyterlab_scheduler) (0.17.3)
Requirement already satisfied: setuptools in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab~=2.0->jupyterlab_scheduler) (49.6.0.post20200814)
Requirement already satisfied: traitlets>=4.2.1 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (4.3.3)
Requirement already satisfied: nbformat in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (5.1.2)
Requirement already satisfied: terminado>=0.8.3 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.9.2)
Requirement already satisfied: Send2Trash>=1.5.0 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (1.5.0)
Requirement already satisfied: ipython-genutils in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.2.0)
Requirement already satisfied: jupyter-client>=5.3.4 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (6.1.6)
Requirement already satisfied: jupyter-core>=4.6.1 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (4.6.1)
Requirement already satisfied: pyzmq>=17 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (19.0.1)
Requirement already satisfied: argon2-cffi in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (20.1.0)
Requirement already satisfied: ipykernel in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (5.3.4)
Requirement already satisfied: nbconvert in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (6.0.7)
Requirement already satisfied: prometheus-client in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.9.0)
Requirement already satisfied: python-dateutil>=2.1 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jupyter-client>=5.3.4->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (2.8.1)
Requirement already satisfied: ansiwrap in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from papermill~=2.1->jupyterlab_scheduler) (0.8.4)
Requirement already satisfied: nbclient>=0.2.0 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from papermill~=2.1->jupyterlab_scheduler) (0.5.1)
Requirement already satisfied: tqdm>=4.32.2 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from papermill~=2.1->jupyterlab_scheduler) (4.56.0)
Requirement already satisfied: click in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from papermill~=2.1->jupyterlab_scheduler) (7.1.2)
Requirement already satisfied: tenacity in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from papermill~=2.1->jupyterlab_scheduler) (6.3.1)
Requirement already satisfied: black in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from papermill~=2.1->jupyterlab_scheduler) (20.8b1)
Requirement already satisfied: entrypoints in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from papermill~=2.1->jupyterlab_scheduler) (0.3)
Requirement already satisfied: pyyaml in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from papermill~=2.1->jupyterlab_scheduler) (5.4.1)
Requirement already satisfied: nest-asyncio in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from nbclient>=0.2.0->papermill~=2.1->jupyterlab_scheduler) (1.5.1)
Requirement already satisfied: async-generator in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from nbclient>=0.2.0->papermill~=2.1->jupyterlab_scheduler) (1.10)
Requirement already satisfied: ptyprocess in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from terminado>=0.8.3->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.6.0)
Requirement already satisfied: decorator in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (4.4.2)
Requirement already satisfied: textwrap3>=0.9.2 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from ansiwrap->papermill~=2.1->jupyterlab_scheduler) (0.9.2)
Requirement already satisfied: cffi>=1.0.0 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from argon2-cffi->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (1.14.4)
Requirement already satisfied: pycparser in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (2.20)
Requirement already satisfied: pathspec<1,>=0.6 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from black->papermill~=2.1->jupyterlab_scheduler) (0.8.1)
Requirement already satisfied: toml>=0.10.1 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from black->papermill~=2.1->jupyterlab_scheduler) (0.10.2)
Requirement already satisfied: typed-ast>=1.4.0 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from black->papermill~=2.1->jupyterlab_scheduler) (1.4.2)
Requirement already satisfied: regex>=2020.1.8 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from black->papermill~=2.1->jupyterlab_scheduler) (2020.11.13)
Requirement already satisfied: appdirs in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from black->papermill~=2.1->jupyterlab_scheduler) (1.4.4)
Requirement already satisfied: mypy-extensions>=0.4.3 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from black->papermill~=2.1->jupyterlab_scheduler) (0.4.3)
Requirement already satisfied: typing-extensions>=3.7.4 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from black->papermill~=2.1->jupyterlab_scheduler) (3.7.4.3)
Requirement already satisfied: ipython>=5.0.0 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from ipykernel->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (7.18.1)
Requirement already satisfied: pygments in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (2.6.1)
Requirement already satisfied: pickleshare in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.7.5)
Requirement already satisfied: jedi>=0.10 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.17.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (3.0.7)
Requirement already satisfied: pexpect>4.3 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (4.8.0)
Requirement already satisfied: backcall in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.2.0)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.2.5)
Requirement already satisfied: mistune<2,>=0.8.1 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (1.4.3)
Requirement already satisfied: defusedxml in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.6.0)
Requirement already satisfied: bleach in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (3.2.3)
Requirement already satisfied: testpath in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.4.4)
Requirement already satisfied: jupyterlab-pygments in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.1.2)
Requirement already satisfied: packaging in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (20.8)
Requirement already satisfied: webencodings in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from packaging->bleach->nbconvert->notebook>=4.3.1->jupyterlab~=2.0->jupyterlab_scheduler) (2.4.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from requests->jupyterlab-server<2.0,>=1.1.5->jupyterlab~=2.0->jupyterlab_scheduler) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from requests->jupyterlab-server<2.0,>=1.1.5->jupyterlab~=2.0->jupyterlab_scheduler) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from requests->jupyterlab-server<2.0,>=1.1.5->jupyterlab~=2.0->jupyterlab_scheduler) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/jupyter_hub/lib/python3.8/site-packages (from requests->jupyterlab-server<2.0,>=1.1.5->jupyterlab~=2.0->jupyterlab_scheduler) (2020.12.5)

$ jupyter labextension install jupyterlab_scheduler
An error occured.
ValueError: "/home/oskr/jupyterlab_scheduler" is not a valid extension:
Missing extension module "lib/plugin.js"
See the log file for details:  /tmp/jupyterlab-debug-_jldw98d.log
```
And here is the content of the log file
```
$ cat /tmp/jupyterlab-debug-_jldw98d.log
Node v10.19.0

Yarn configuration loaded.
> /usr/bin/npm pack jupyterlab_scheduler
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/jupyterlab_scheduler - Not found
npm ERR! 404 
npm ERR! 404  'jupyterlab_scheduler@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oskr/.npm/_logs/2021-01-28T05_41_44_993Z-debug.log

Traceback (most recent call last):

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 138, in run_task
    return any([

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 139, in <listcomp>
    install_extension(

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/commands.py", line 1499, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/commands.py", line 1578, in _extract_package
    raise ValueError(msg % source)

ValueError: "jupyterlab_scheduler" is not a valid npm package

Exiting application: jupyter
```
Could we reopen the issue? or should we open a new one?
