### ISSUE TITLE
Missing extension module "lib/plugin.js"

### ISSUE THREAD

**Issue by oskrdt** [tiburon-security/jupyterlab_scheduler#9]
I followed the steps to try to install the development version. 
Cloned repository and built it. Here is the output
```
$ npm install
npm WARN deprecated @mattiasbuelens/web-streams-polyfill@0.2.1: moved to web-streams-polyfill@2.0.0
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> core-js@3.8.3 postinstall /home/oskr/jupyterlab_scheduler/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ppc64"})
npm WARN @lumino/coreutils@1.5.3 requires a peer of crypto@1.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.2.2 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN css-loader@3.6.0 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@4.3.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.1.2 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

added 615 packages from 1211 contributors and audited 621 packages in 30.752s

41 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
I tried to install the extension and here is the output
```
$ jupyter labextension install .
An error occured.
ValueError: "/home/oskr/jupyterlab_scheduler" is not a valid extension:
Missing extension module "lib/plugin.js"
See the log file for details:  /tmp/jupyterlab-debug-718vj1uv.log
```
And here is the complete log
```
$ cat /tmp/jupyterlab-debug-718vj1uv.log
Node v10.19.0

Yarn configuration loaded.
> /usr/bin/npm pack /home/oskr/jupyterlab_scheduler
npm notice 
npm notice package: jupyterlab_scheduler@0.1.3
npm notice === Tarball Contents === 
npm notice 186B   .babelrc                                
npm notice 0      style/plugin.css                        
npm notice 406B   MANIFEST.in                             
npm notice 7.4kB  src/AddJob.js                           
npm notice 882B   src/api.js                              
npm notice 2.8kB  src/plugin.js                           
npm notice 3.8kB  src/ShowJobs.js                         
npm notice 1.3kB  src/ViewLog.js                          
npm notice 108B   jupyter-config/jupyterlab_scheduler.json
npm notice 1.7kB  package.json                            
npm notice 2.4kB  README.md                               
npm notice 44.3kB screenshots/context-menu.png            
npm notice 7.8kB  screenshots/main-menu.png               
npm notice 28.0kB screenshots/schedule-job.png            
npm notice 14.1kB screenshots/scheduled-jobs.png          
npm notice 46.3kB screenshots/view-logs.png               
npm notice 570B   jupyterlab_scheduler/__init__.py        
npm notice 71B    jupyterlab_scheduler/_version.py        
npm notice 6.3kB  jupyterlab_scheduler/handlers.py        
npm notice 3.9kB  setup.py                                
npm notice 167B   pyproject.toml                          
npm notice 18B    requirements.txt                        
npm notice === Tarball Details === 
npm notice name:          jupyterlab_scheduler                    
npm notice version:       0.1.3                                   
npm notice filename:      jupyterlab_scheduler-0.1.3.tgz          
npm notice package size:  141.9 kB                                
npm notice unpacked size: 172.5 kB                                
npm notice shasum:        b034801e2c4bf88c018dba716c934755ca528fe5
npm notice integrity:     sha512-a/F22xvU3G0tH[...]gJv31W6zao+kA==
npm notice total files:   22                                      
npm notice 
jupyterlab_scheduler-0.1.3.tgz

Traceback (most recent call last):

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 138, in run_task
    return any([

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 139, in <listcomp>
    install_extension(

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/opt/conda/envs/jupyter_hub/lib/python3.8/site-packages/jupyterlab/commands.py", line 1520, in _install_extension
    raise ValueError(msg)

ValueError: "/home/oskr/jupyterlab_scheduler" is not a valid extension:
Missing extension module "lib/plugin.js"

Exiting application: jupyter
```

**Comment by maxmcd** [comment]
I think you need to run
```
npm install
npm run build:lib
jupyter labextension install .
```
